###
//creating one
POST http://localhost:3000/admins

Content-Type: application/json

{
  "hashedPassword": "your_password",
  "username": "your_usveriname"

}


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
###
//getting all
GET  http://localhost:3000/admins


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
###
//getting one
GET  http://localhost:3000/admins/65be46451982a457109796cc


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
###
//updating one
PATCH http://localhost:3000/admins/65be46451982a457109796cc

Content-Type: application/json
{

  "username": "your_useringfjfjakme",
    "password": "your_password",

}


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
###
//deleting one
DELETE   http://localhost:3000/admins/65ba90827df92d9c9ad8c6b8